language: java
sudo: false

git:
  depth: false

jdk:
  - oraclejdk8
  - openjdk8

addons:
  sonarcloud:
    organization: "reggert-github"
    token:
      secure: "AcVZ63rs8my83/2zktiO5GwqNfdqiAM0OMbsfLTBS0W634Jx/5Bm+kq/CbXibWP5RomTwySsf1Mi+Hyu4chJhANiFVw1FYiPZLjS8Bo3XNfcKQ+Qbaa8bn0RETpIO+0lglEJSy493Sq/QpLeK4rPSG5VGbB48exT++s35JO+Nm8="
script:
  -  mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
